### ISSUE TITLE
Utilisation des notations array

### ISSUE THREAD

**Issue by UbikZ** [Galilee/chili-php-sdk#1]
On utilise les notations array suivante dans toute l'application:

``` php
$array = [];
```

On pourrait être en PHP5.3.x dans une grande majorité d'applications.
Il faudrait préférer la notation classique suivante: 

``` php
$array = array();
```

cf. http://php.net/manual/fr/language.types.array.php

**Comment by vguraugalilee** [comment]
Ok, c'est corrigé !
