### ISSUE TITLE
Soucis au niveau des "returns"

### ISSUE THREAD

**Issue by UbikZ** [Galilee/chili-php-sdk#2]
On utilise pas de "return;" (void) si dans la même fonction on return qqch d'un type différent.

ex: chili-php-sdk/src/Manager/Document.php

**Comment by lc-galilee** [comment]
zgerhogrzhuogerjiogrjiogre
zgerhogrzhuogerjiogrjiogre
zgerhogrzhuogerjiogrjiogre
zgerhogrzhuogerjiogrjiogre
zgerhogrzhuogerjiogrjiogre
zgerhogrzhuogerjiogrjiogre
zgerhogrzhuogerjiogrjiogre
zgerhogrzhuogerjiogrjiogre
zgerhogrzhuogerjiogrjiogre
zgerhogrzhuogerjiogrjiogre

**Comment by lc-galilee** [comment]
gerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjiogergerjiojiorgejiogerjioger
