### ISSUE TITLE
Publication packagist ?

### ISSUE THREAD

**Issue by dpiquet** [Galilee/chili-php-sdk#3]
Bonjour,

Est-il prévu de publier cette lib sur packagist afin de simplifier son déploiement ?

Cordialement,

**Comment by geraudi** [comment]
Bonjour,

Effectivement c'est prévu dès qu'une la version stable sera finalisée.

Cordialement

**Comment by geraudi** [comment]
Bonjour,

La lib est (afin) sur packagist.
